publisher_ur5_3d_construction_move_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 15
    trajectory_duration: 12
    
    goal_names: ["pos1", "pos2", "pos3", "pos4","pos5"]

    #ZYZ Euler angle(d) and position(m)
    pos1: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.5]    # (0) 0 degree
    pos2: [0.0, 150.0, 90.0, 0.22, -0.10, 0.32]    # (12) 30 degree; x - 0.277; y
    pos3: [-90.0, -150.0, 0.0, 0.42, -0.35, 0.32]    # (7) 30 degree; x ; y - 0.277
    pos4: [0.0, -150.0, 60.0, 0.60, -0.10, 0.28]    # (1) 30 degree; x + 0.24
    pos5: [90.0, -150.0, 90.0, 0.4, 0.15, 0.32]    # (6) 30 degree; x ; y + 0.277
    
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]

timer_node_image_capture:
  ros__parameters:

    image_capture_number: 12
    wait_sec_between_image_capture: 10
    image_capture_time: 8

      
      
