publisher_ur5_3d_construction_move_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 15
    trajectory_duration: 12
    
    goal_names: ["pos1", "pos2"]

    #ZYZ Euler angle(d) and position(m)
    pos1: [-90.0, 90.9, 0.0, 0.45, -0.10, 0.5]    # (0) 0 degree
    pos2: [-90.0, 90.9, 0.0, 0.45, -0.10, 0.5]
    
    final_goal1: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.30]    
    final_goal2: [-90.0, 179.9, 0.0, 0.7, -0.10, 0.25]
    
    objects_num: 2
    
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]


      
      
