publisher_vision_based_grasp_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 12
    trajectory_duration: 8
    
    goal_names: ["object0", "object1", "object2", "object3", "object4", "object5"]

    #ZYZ Euler angle(d) and position(m)

    ## original goal from MVBB
    #object0: [-52.6,  179.9,  0.0,  0.26,  0.0756, -0.032]    #object_idx = 0
    #object1: [-41.23, 102.54,  -6.63,  0.408,  0.062, -0.0114]    #object_idx = 3
    #object2: [-100.0,  90.0,  0.0,  0.33, -0.076,  0.05]     #object_idx = 2
    #object3: [-89.0,  178.0,  0.0,  0.475, -0.086, -0.037]    #object_idx = 5
    #object4: [-118.0,  179.9,  0.0,  0.43,  -0.29, -0.037]   #object_idx = 4
    #object5: [-118.0,  90.0,  0.0,  0.3, -0.28, -0.03]    #object_idx = 1
    
    ## Modified goal
    object0: [-55.0,  179.9,  0.0,  0.29,  0.09, -0.03]    #object_idx = 0,  x + 0.03, y + 0.015
    object1: [-35.0, 110.0,  -8.0,  0.44,  0.09, -0.015]    #object_idx = 3, x + 0.04, y + 0.03
    object2: [-98.0,  90.0,  0.0,  0.347, -0.06,  0.05]     #object_idx = 2, x + 0.015, y+ 0.02
    object3: [-89.0,  178.0,  0.0,  0.5, -0.086, -0.0364]    #object_idx = 5, x + 0.03
    object4: [-115.0,  179.9,  0.0,  0.45,  -0.285, -0.0364]   #object_idx = 4,  x + 0.03, y + 0.015
    object5: [-118.0,  90.0,  0.0,  0.315, -0.245, -0.029]    #object_idx = 1,  + 0.015, y + 0.035

    start_goal: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.445] 
    intermediate_goal: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.3]    
    final_goal: [-90.0, 179.9, 0.0, 0.72, -0.15, 0.12]     
    
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]


      
      
