publisher_vision_based_grasp_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 14
    trajectory_duration: 12
    
    goal_names: ["object0", "object1", "object2", "object3", "object4", "object5"]

    #ZYZ Euler angle(d) and position(m)
    object0: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]    
    object1: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]    
    object2: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]    
    object3: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]    
    object4: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]   
    object5: [-90.0, 179.9, 0.0, 0.0, 0.0, 0.0]    
    
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]


      
      
